apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal-services
resources:
- namespace.yaml
- servers-transport.yaml
- ./homeassistant/homeassistant.yaml
- ./uptime-kuma/uptime-kuma.yaml
