---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore
resources:
  - https://github.com/piraeusdatastore/piraeus-operator/config/default?ref=v2.10.2
  - https://github.com/piraeusdatastore/piraeus-operator/config/extras/monitoring?ref=v2.10.2
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v8.4.0
  - https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v8.4.0
patches:
  - target:
      group: piraeus.io
      version: v1
      kind: LinstorSatellite
    patch: |-
      - op: replace
        path: /spec/deletionPolicy
        value: Evacuate
