apiVersion: v1
kind: Secret
metadata:
    name: oplog-mongodb-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:emn541OE6wfKW5UOjCB1fon4iB+9T7i5IUfgJ482Y54=,iv:nKfqKvFjoFEubYQRklLXmBk9PC/f+0elpnPhdeNcr4g=,tag:0qBWXwGOJm5eEtsvJsYiYw==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2dDOWRMcmVQUFdwOEFG
            cDU2SnJRQVZGQm8wVTA0SkR2MWNuNlludjFvCnFaSmlFVW5QUkhseGZNbnRUSXlD
            dTgwekhHSlJWVDM3ZFR5UVdubzI3YWcKLS0tIFNZNm5sUEI3WlNnMTZzNDEzQUhH
            cUQ1a1JrMXE1c0xGbW11dnZLd0hlNEEKoJAuhIMYhdwy/nEzTzFD8ZM8UHHkaawX
            WTsNx0vVcFkBDWm8wmD9rrDge2ZgNilMitVmcYIIcDkdFNNhQ7xsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T22:37:28Z"
    mac: ENC[AES256_GCM,data:1c9nQ91txN/8uH71pCqusdXSFupEkArWIiuVydAK0a83rr9gdduHDqdF5mj3b9/N5KAMOkvvFI+qEDgPBugWZlqjC/dlMnea2yTDInB/zRMICngtQnZkz1xm1rNVcVKHdb8Pz6dXmgNZos4yKyKu7BOfan+PNbp+lPV5j3VSXWA=,iv:FVhFN2EZ76LazdXSEPfrrRlrzriCnyepEEKIqA0wfhw=,tag:5Eo7zW3wx53rPjZnBuzrNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
