---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongodb
resources:
  - ops-manager-credentials-secret.yaml
  - ops-manager.yaml
  - ops-manager-ingressroute.yaml
  - oplog-ops-manager-config.yaml
  - oplog-ops-manager-secret.yaml
  - oplog-mongodb-secret.yaml
  - oplog-mongodb.yaml
