apiVersion: v1
kind: ConfigMap
metadata:
  name: oplog-ops-manager-config
  namespace: mongodb
data:
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080
  projectName: oplog
  orgId: 68ed7f6135b47e342a2dec58
