apiVersion: v1
kind: Secret
metadata:
    name: oplog-ops-manager-secret
    namespace: mongodb
type: Opaque
stringData:
    publicKey: ENC[AES256_GCM,data:SA29g31Jnj0=,iv:ZfgzyWz4U1jTzeV4I8f/am64JvTjystuVRwHyjPM4Mo=,tag:RVSWtUptr0NZmlW42cBdkw==,type:str]
    privateKey: ENC[AES256_GCM,data:Our46iVIqZe+IgSUVsh5gjntVw+g6QehupCTv5Ms8dLNi5l+,iv:6X1SRTBsmeGEdsdqoHjXsUaa83GCbhJFcKEpQ1BJqxo=,tag:ZhVBi0KRIYAKnM4hfMD8TQ==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZd1g1MmU2MmNnSjE3ajNp
            Znoyd3JzV1ZITFhVb0tzQnR5cUR5cFVnRWg4Citvb1I5blE4alVaOFVSY2p1d3hQ
            bXJQeWhta0FQckJhZDlwSUljM2VEY2MKLS0tIHlxeDAyYUhIWGMzL1dQQ1FGeWZS
            UENBbmZnUkxRZlVXZkh6eGRQMktxNkEKuZirDwGCuDu+ZyBrbncvqovIl8QE8Z/z
            0L92K0kF9qBoOXQec48Z/zT2xeWDPa4pW7/mdyfA8O/cnWworluexQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T22:54:07Z"
    mac: ENC[AES256_GCM,data:dv25zBfz6Ts4wdepzVK/sbc9D1gZLEkLiTH98j7damNhjl9y4GdqzRAmqj1LjaXZFfC5Bm06CWuUI9PWZO9P+wmwx+tOZ43xVJ9fgpwCDtiXsbumDJEhTvjozsdveRppwHLCMOc+5+HaWcZ3hQjQRyKPV9gwNlwRDA0D0Pu3ylk=,iv:+jpOTApnW/ZMwf7Q+t6AvsjAYhPNon3Tp2UJpHQttRc=,tag:LWQxcRw54AHuXBsR3+baUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
