apiVersion: v1
kind: Secret
metadata:
    name: oplog-ops-manager-secret
    namespace: mongodb
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:kFC+uDtME48=,iv:mTcaiNoaXAjsNmu1qJ7wIgcjLWxv9pF+eTv+E4SaOT4=,tag:pfH/iCluPTrhpNRkYMBBpA==,type:str]
    publicApiKey: ENC[AES256_GCM,data:rX/mrcHgll+N8ITLfnyYu3Ks4vXc1lI7PygYPn6izkW3oi4H,iv:f+O9jORjozEnXtJaivf6ftLRq687bM+Xnh+NmJFNQgE=,tag:SmGGLg9gmXPIaaJOGL9YiQ==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZd1g1MmU2MmNnSjE3ajNp
            Znoyd3JzV1ZITFhVb0tzQnR5cUR5cFVnRWg4Citvb1I5blE4alVaOFVSY2p1d3hQ
            bXJQeWhta0FQckJhZDlwSUljM2VEY2MKLS0tIHlxeDAyYUhIWGMzL1dQQ1FGeWZS
            UENBbmZnUkxRZlVXZkh6eGRQMktxNkEKuZirDwGCuDu+ZyBrbncvqovIl8QE8Z/z
            0L92K0kF9qBoOXQec48Z/zT2xeWDPa4pW7/mdyfA8O/cnWworluexQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T22:38:49Z"
    mac: ENC[AES256_GCM,data:PSoASUaqMk0+UjNiuc3viTmsxfsbzDgJYSztxDWI4Kxlk9RD0A2b2DjtNIGHEJE0EQ8DneFetLsr8KJmFm+zbfuzCzsukmD7ZOSWlOS8UwvMqlWWU5dky6nEBYYxO1HVJdwPlbVQWCveA2bhmGwQpk38gmhXpOHzdhb8gGo8LTg=,iv:TXzPNNf6ix8427ZF7M2cCOqzFX9w2Mq8Zt1JKavqH0w=,tag:XXDj3w6Fs4Ih8lqI5wdMCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
