apiVersion: v1
kind: Secret
metadata:
    name: opnsense-02-secret
type: Opaque
stringData:
    OPNSENSE_EXPORTER_OPS_PROTOCOL: ENC[AES256_GCM,data:ZrtyfXA=,iv:uqdTNQMfPgWRdpHsRXSAr0V9cWELO+Z5uHarDICw+oQ=,tag:t13VLmhuHQI1YoLjxM3muQ==,type:str]
    OPNSENSE_EXPORTER_OPS_API: ENC[AES256_GCM,data:GmDDqLKn68HqwTQWsDwDeWG24ss=,iv:Ud934+zZhKqFP1Xwag4pA6dQdXGaicNPrem4WLf11J4=,tag:+Zt3bcp0VAZbs09KJlQYpw==,type:str]
    OPNSENSE_EXPORTER_OPS_API_KEY: ENC[AES256_GCM,data:jF8U/zfL6n6EPnYMkzhWDfu/vwzeqh7l/dG02m6vSj6eJ4g4idNaAwcIot0rBEIoiIf6dkCWOTV3N1JXqiXxdInUj1gOZT4fdbrOp2sG+oY=,iv:VEpN17o1Jd3ypL6LrioHBGcNR643rZ6qvNgZE0X72Us=,tag:bUl3qWTx4r0xzhMFoADZrA==,type:str]
    OPNSENSE_EXPORTER_OPS_API_SECRET: ENC[AES256_GCM,data:JBlorUl/j9DbNQElvQRNVAR75tSIeGCGj2SqJRtEJ05/7vcivRYFBuo/+nH5FIBeI6qnSSfpslY4bJADmpAlOZwvv4GGZ0Swd03tGr11d+k=,iv:QRpCTVP/kwJJIPDF+WW6v7TYkR2FtTTnb2sNmOWgHyM=,tag:Kzjh7ZFJrTvdl0OE2cEw5Q==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2dDOWRMcmVQUFdwOEFG
            cDU2SnJRQVZGQm8wVTA0SkR2MWNuNlludjFvCnFaSmlFVW5QUkhseGZNbnRUSXlD
            dTgwekhHSlJWVDM3ZFR5UVdubzI3YWcKLS0tIFNZNm5sUEI3WlNnMTZzNDEzQUhH
            cUQ1a1JrMXE1c0xGbW11dnZLd0hlNEEKoJAuhIMYhdwy/nEzTzFD8ZM8UHHkaawX
            WTsNx0vVcFkBDWm8wmD9rrDge2ZgNilMitVmcYIIcDkdFNNhQ7xsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T22:21:39Z"
    mac: ENC[AES256_GCM,data:gSlCox3OgvRHOtl4+rZZZPyFYgvtLDF+P4T2JEjm8G9xTr+xNEkF0FsSvMBDu7GuI0c9JHN+Xx8UyT8g2GIS2nlPxrYBJ4aEfLLivPNXmJ5aUHRN6V0aHnP7/9GceBMXrH22kyTCL10l1GN08xBPJdYMcjZdunXWYYFtevPUDXU=,iv:FRf/1JGSofzg4deyVlJs5yrGrPGCArIiiQ1aOarMAg0=,tag:Y95X/K4QVEiNucH3MeLPww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
