apiVersion: v1
kind: Secret
metadata:
    name: opnsense-01-secret
type: Opaque
stringData:
    OPNSENSE_EXPORTER_OPS_PROTOCOL: ENC[AES256_GCM,data:ZeV3UY4=,iv:ASJkzTKAJkxXMn+eMscQhrh8qYeYzdUEGWuLWXpY9z0=,tag:tDSYz0zXE0CX9iNN4rsy9w==,type:str]
    OPNSENSE_EXPORTER_OPS_API: ENC[AES256_GCM,data:9HnEGwZncK7yAN/Y/oyqdnwQsy4=,iv:Feaxp6VtofRbJVW8hAB+C1xbkR8KSpxPnrCgsQim44Y=,tag:OXjs9N3ipopAZysDYqs05w==,type:str]
    OPNSENSE_EXPORTER_OPS_API_KEY: ENC[AES256_GCM,data:iYdzpI79bK4OyaJlys8INuygWW5SqMpFo2Ejj2VFNxA3vlZt8dOo7dmH+Na0wGBRgkro16GXpLRvZ6tDhRpa0VBaQyyjTK8e5g3K2j/kzUg=,iv:Z2ILHjWla0alqk7JH+Z7hYS/i0nzogM23KIhuqp3Q4s=,tag:IG2T21Nlcpm2dIoRs6lInA==,type:str]
    OPNSENSE_EXPORTER_OPS_API_SECRET: ENC[AES256_GCM,data:oyYDUzzG0OZgBSpMNFFj44lx5WWKXQHskLzHUi6uceoXZ5ezvmIYHaaqEKDEyRWMCQFtv7ZK7mwcou8zl+7UTmlxxhq3Aw5w4aYkYycufgk=,iv:3TfrSEQUqIs1odkvsc9g4s7rT2/sMd3LxmZTb8FSu/A=,tag:FWLlFIRUHCVvmuLLrQgyXQ==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2dDOWRMcmVQUFdwOEFG
            cDU2SnJRQVZGQm8wVTA0SkR2MWNuNlludjFvCnFaSmlFVW5QUkhseGZNbnRUSXlD
            dTgwekhHSlJWVDM3ZFR5UVdubzI3YWcKLS0tIFNZNm5sUEI3WlNnMTZzNDEzQUhH
            cUQ1a1JrMXE1c0xGbW11dnZLd0hlNEEKoJAuhIMYhdwy/nEzTzFD8ZM8UHHkaawX
            WTsNx0vVcFkBDWm8wmD9rrDge2ZgNilMitVmcYIIcDkdFNNhQ7xsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T22:22:07Z"
    mac: ENC[AES256_GCM,data:mB4WizIeRBiAk10qOjSXUfLd9zluVkhh/sVI0s6tO47zttSZWuybO1qqRS78VBnpWXj6gFhQj5znq7VJ64+sh69Y1eDZTZV/Aw77OmHTV4jM5wVVmXO385wmjQN9PnRDgJUpZrDgcjGEnTc2poVB7FJ3iUU1dMQYiDHbRxXhl7U=,iv:mh29H4/4c+6GhMaMrJSCWEhe+WzXvR8lLC/YuLcOxEw=,tag:A2Xs5Mh3TlzbGaB4f8BoFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
